kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: rhsso
  namespace: rhsso-lab
  labels:
    app: rhsso
  managedFields:
    - manager: OpenAPI-Generator
      operation: Update
      apiVersion: build.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
              'f:env': {}
            'f:type': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-06-19T12:59:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'rhsso:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: TZ
          value: UTC+3
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        http://<your-token-git>@<your-url-git>/<your-project>/<your-repository>.git
      ref: customize-datasource
  triggers:
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
